services:
  web:
    image: elemental/inventory
    build: .
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "mysql-data:/var/lib/mysql"

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mysql-data: