require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/smartphones", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Smartphone. As you add validations to Smartphone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Smartphone.create! valid_attributes
      get smartphones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      smartphone = Smartphone.create! valid_attributes
      get smartphone_url(smartphone)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_smartphone_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      smartphone = Smartphone.create! valid_attributes
      get edit_smartphone_url(smartphone)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Smartphone" do
        expect {
          post smartphones_url, params: { smartphone: valid_attributes }
        }.to change(Smartphone, :count).by(1)
      end

      it "redirects to the created smartphone" do
        post smartphones_url, params: { smartphone: valid_attributes }
        expect(response).to redirect_to(smartphone_url(Smartphone.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Smartphone" do
        expect {
          post smartphones_url, params: { smartphone: invalid_attributes }
        }.to change(Smartphone, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post smartphones_url, params: { smartphone: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested smartphone" do
        smartphone = Smartphone.create! valid_attributes
        patch smartphone_url(smartphone), params: { smartphone: new_attributes }
        smartphone.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the smartphone" do
        smartphone = Smartphone.create! valid_attributes
        patch smartphone_url(smartphone), params: { smartphone: new_attributes }
        smartphone.reload
        expect(response).to redirect_to(smartphone_url(smartphone))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        smartphone = Smartphone.create! valid_attributes
        patch smartphone_url(smartphone), params: { smartphone: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested smartphone" do
      smartphone = Smartphone.create! valid_attributes
      expect {
        delete smartphone_url(smartphone)
      }.to change(Smartphone, :count).by(-1)
    end

    it "redirects to the smartphones list" do
      smartphone = Smartphone.create! valid_attributes
      delete smartphone_url(smartphone)
      expect(response).to redirect_to(smartphones_url)
    end
  end
end
